apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - image: my-flask-app:0.0.1
        imagePullPolicy: IfNotPresent
        name: my-flask-app
        ports:
        - containerPort: 5000
